import platform
import numpy as np
import time
import logging
try:
    import smbus
except:
    platform = 'Win'

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def readCpp(file) -> list:
    """
    Converts .cpp script generated by the GMSL CSI tool to a list of writes
    (also lists) that contains only the device address, register address
    and value to be written. 
    """
    writes = []
    try:
        with open(file, 'r') as f:
            for line_number, line in enumerate(f, start=1):
                if line.startswith('0x04'):
                    line = line.replace(' ', '')
                    uncomment = line.split('//')
                    bytes = uncomment[0].split(',')
                    writes.append(bytes2write(bytes[1 : -1]))
                if line.startswith('0x00'):
                    # Handle lines starting with '0x00' if needed
                    pass
    except FileNotFoundError:
        logger.error(f"The file {file} was not found.")
    except Exception as e:
        logger.error(f"An error occurred at line {line_number}: {e}")
    return writes

def readTxt(file):
    return

def readCsv(file):
    return

def bytes2write(bytes) -> list:
    """
    Reformat [DEV, MSB, LSB, VAL]
    to [DEV, REG_16bit, VAL]
    """
    try:
        dev = int(bytes[0], 0)
        msb = int(bytes[1], 0)
        lsb = int(bytes[2], 0)
        val = int(bytes[3], 0)
        return [dev, msb * 256 + lsb, val]
    except (IndexError, ValueError) as e:
        logger.error(f"Error processing bytes: {bytes} - {e}")
        return []

class GMSLi2c:
    def __init__(self, host):
        try:
            self.host = host
            self.DEBUG = False
            self.LOG = False
        except Exception as e:
            logger.error(f"Error initializing GMSLi2c: {e}")
    
    def regRead(self, dev, reg):
        return self.host.regRead(dev, reg)
    
    def regWrite(self, dev, reg, val, mask = 0xff):
        if mask != 0xff:
            rdVal = self.regRead(dev, reg)
            val = (val and mask) or (~mask and rdVal)
        
        self.host.regWrite(dev, reg, val)

        if self.LOG:
            logger.info(f'Writing: dev = {hex(dev)}, reg = {hex(reg)}, val = {hex(val)}')
        if self.DEBUG:
            time.sleep(0.1)
            logger.debug(f'Debug readbck: dev = {hex(dev)}, reg = {hex(reg)}, val = {hex(self.regRead(dev, reg))}')

    def parseFile(self, file):
        logger.info(f"Parsing file: {file}")
        if file.endswith('cpp'):
            seq = readCpp(file)[::-1]
            logger.info(f"Sequence loaded: {seq}")
        
        while seq:
            dev, reg, val = seq.pop()
            logger.info(f"Processing: dev = {hex(dev)}, reg = {hex(reg)}, val = {hex(val)}")

            if dev == 0:
                time.sleep(10e-2)
            else:
                self.regWrite(dev, reg, val)
                logger.info(f"Written: dev = {hex(dev)}, reg = {hex(reg)}, val = {hex(val)}")



class rpii2c:
    def __init__(self, bus = 10):
        self.bus = smbus.SMBus(bus)
    
    def regRead(self, dev, reg):
        dev = dev >> 1
        msb = int(reg / 256)
        lsb = int(reg % 256)
        self.bus.write_byte_data(dev, msb, lsb)
        val = self.bus.read_byte(dev)
        return val

    def regWrite(self, dev, reg, val):
        dev = dev >> 1
        msb = int(reg/256)
        lsb = int(reg%256)
        print(dev)
        print(lsb)
        print(msb)
        print(lsb + val * 256)

        self.bus.write_word_data(dev, msb, lsb + val * 256)
